[window]
startup_mode = "Fullscreen"
# Options: "Windowed", "Maximized", "Fullscreen", "SimpleFullscreen"
# opacity = 0.85
[colors.primary]
background = '#1E1E1E'
foreground = '#ffffff'

# Optional: Adjust the cursor color to match
[colors.cursor]
text = '#000000'
cursor = '#ffffff'

[font]
size = 14.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
